# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dream.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dream.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x64ream.proto\"=\n\x0c\x44reamRequest\x12\r\n\x05layer\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\r\x12\r\n\x05image\x18\x03 \x01(\x0c\"\x1e\n\rDreamResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x32\x33\n\x07\x44reamer\x12(\n\x05\x44ream\x12\r.DreamRequest\x1a\x0e.DreamResponse\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DREAMREQUEST = _descriptor.Descriptor(
  name='DreamRequest',
  full_name='DreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layer', full_name='DreamRequest.layer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel', full_name='DreamRequest.channel', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='DreamRequest.image', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=76,
)


_DREAMRESPONSE = _descriptor.Descriptor(
  name='DreamResponse',
  full_name='DreamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='DreamResponse.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['DreamRequest'] = _DREAMREQUEST
DESCRIPTOR.message_types_by_name['DreamResponse'] = _DREAMRESPONSE

DreamRequest = _reflection.GeneratedProtocolMessageType('DreamRequest', (_message.Message,), dict(
  DESCRIPTOR = _DREAMREQUEST,
  __module__ = 'dream_pb2'
  # @@protoc_insertion_point(class_scope:DreamRequest)
  ))
_sym_db.RegisterMessage(DreamRequest)

DreamResponse = _reflection.GeneratedProtocolMessageType('DreamResponse', (_message.Message,), dict(
  DESCRIPTOR = _DREAMRESPONSE,
  __module__ = 'dream_pb2'
  # @@protoc_insertion_point(class_scope:DreamResponse)
  ))
_sym_db.RegisterMessage(DreamResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class DreamerStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Dream = channel.unary_unary(
          '/Dreamer/Dream',
          request_serializer=DreamRequest.SerializeToString,
          response_deserializer=DreamResponse.FromString,
          )


  class DreamerServicer(object):

    def Dream(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_DreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Dream': grpc.unary_unary_rpc_method_handler(
            servicer.Dream,
            request_deserializer=DreamRequest.FromString,
            response_serializer=DreamResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Dreamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaDreamerServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def Dream(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaDreamerStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def Dream(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    Dream.future = None


  def beta_create_Dreamer_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('Dreamer', 'Dream'): DreamRequest.FromString,
    }
    response_serializers = {
      ('Dreamer', 'Dream'): DreamResponse.SerializeToString,
    }
    method_implementations = {
      ('Dreamer', 'Dream'): face_utilities.unary_unary_inline(servicer.Dream),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Dreamer_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('Dreamer', 'Dream'): DreamRequest.SerializeToString,
    }
    response_deserializers = {
      ('Dreamer', 'Dream'): DreamResponse.FromString,
    }
    cardinalities = {
      'Dream': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'Dreamer', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
