# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import dream_pb2 as dream__pb2


class DreamerStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Dream = channel.unary_unary(
        '/Dreamer/Dream',
        request_serializer=dream__pb2.DreamRequest.SerializeToString,
        response_deserializer=dream__pb2.DreamResponse.FromString,
        )


class DreamerServicer(object):

  def Dream(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DreamerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Dream': grpc.unary_unary_rpc_method_handler(
          servicer.Dream,
          request_deserializer=dream__pb2.DreamRequest.FromString,
          response_serializer=dream__pb2.DreamResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Dreamer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
